firebolt-db/firebolt-go-sdk

.github/workflows/integration-tests.yml, .github/workflows/nightly.yml, README.md, auth.go, auth_integration_test.go, client.go, client_integration_test.go, client_test.go, connection.go, connection_integration_test.go, connection_test.go, driver.go, driver_integration_test.go, driver_test.go, dsn.go, result.go, rows.go, rows_test.go, statement.go, utils.go, utils_test.go
In this review I added all the changes from the [Big PR: 22](https://github.com/firebolt-db/firebolt-go-sdk/pull/22 ). Due to the nature of post-factum review, I wasn't able to sync the review with the comments.
=> fix: add PR-related fixes

.github/workflows/integration-tests.yml, .github/workflows/nightly.yml, .legitignore, auth.go, auth_integration_test.go, client.go, client_test.go, contentTypes.go, driver_integration_test.go, urls.go
What it does:
- Add support for Service Account
=> feat: add support for service account

.github/workflows/integration-tests.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, auth_integration_test.go, driver_integration_test.go, go.mod, go.sum
- Add system engine integration tests
- Change nightlies to use staging (instead of dev) because dev is unstable
- Add the option to switch env using GHA
=> test: (FIR-16861) add system engine integration tests

connection_integration_test.go, driver_integration_test.go, rows.go, rows_test.go, statement_test.go, utils_test.go
=> feat(FIR-18759): pgdate tiemstamp(n)tz support

.github/workflows/integration-tests.yml
`inputs.<name>` works for both workflow_dispatch and workflow_call.
=> ci: Fix integration test input

connection_integration_test.go, rows.go, rows_test.go
Ticket: https://packboard.atlassian.net/browse/FIR-16856
=> feat: Add support for new boolean type

client.go, rows.go, rows_test.go
Switched to support new `JSON_Compact` output format. Fixed unit and integration tests
https://github.com/firebolt-db/firebolt-go-sdk/actions/runs/4064398318
=> feat: Fir 15408 new output format stbu

connection_integration_test.go
Old set command no longer available
=> test: Fix set command test

.github/workflows/code-check.yml, .github/workflows/nightly-v1.yml, .github/workflows/pull-request.yml, .github/workflows/release-v1.yml, .github/workflows/release-workflow.yml, README.md, auth.go, auth_integration_test.go, client.go, client_integration_test.go, client_test.go, connection_integration_test.go, driver.go, driver_integration_test.go, dsn.go, dsn_test.go, urls.go
Rebased version of https://github.com/firebolt-db/firebolt-go-sdk/pull/55
Correcting base branch of #59
=> feat: Fir 21174 new identity support

connection_integration_test.go, rows.go
DATE_EXT and TIMESTAMP_EXT have been deprecated
=> test: Remove deprecated types

connection_integration_test.go
Fixed SQL in date integration test
=> test: Fix date integration test

README.md
Update install command to install from 1.x branch
=> docs: Update install command

client.go, client_base.go, client_test.go, client_v0.go, client_v0_test.go, driver_integration_test.go
FIR-28765
404 from those endpoints means there are issues with the account. Returning a meaningful error.
=> fix: Better error handling when account is not correct

connection.go, connection_integration_test.go, utils_test.go
Removed advanced_mode and hidden_query parameters usage from code and tests
=> fix: Fir 28039 remove advanced mode and hidden query

.github/workflows/nightly-v2.yml
Fixed v2 nightly to use staging secrets for staging environment (it was using dev secrets)
=> ci: fix nightly secrets

connection_integration_test.go, driver_integration_test.go, driver_integration_v0_test.go
Fixed existing inf and nan tests by removing zero division queries. Extended tests to cover all supported values
=> test: fix and extend inf and nan tests

connection_common_integration_test.go, driver_integration_test.go, driver_integration_v0_test.go
Added long query test execution time measurement and verification that it's more than 350sec.
=> test: add long query runtime verification

driver_integration_test.go, driver_integration_v0_test.go
Added cleanup scripts for system engine tests
=> test: add system engine tests cleanup

connection_common_integration_test.go, utils.go, utils_test.go
Updated bytea formatting according to recent changes
=> fix: update bytea type formatting

.github/workflows/integration-tests-v2.yml, client.go, client_integration_test.go, connection_integration_test.go, driver_integration_test.go, driver_integration_v0_test.go, driver_options_integration_test.go, go.mod, go.sum
Integration tests all green: https://github.com/firebolt-db/firebolt-go-sdk/actions/runs/9462481848
=> refactor(FIR-33560): Remove redundant and obsolete tests

connection_integration_test.go
Due to GO SDK not supporting multistatements the cleanup query was failing.
However, since it's in a defer statement no error checking was done and we just succeeded.
=> test: Fix db cleanup bug

driver_integration_test.go
Error has changed slightly and we're failing. Adding more robust check, which hopefully will last longer.
=> test: More robust structured error test

.github/workflows/code-check.yml, .github/workflows/integration-tests-v1.yml, .github/workflows/integration-tests-v2.yml, .github/workflows/nightly-v1.yml, .github/workflows/nightly-v2.yml, connection_common_integration_test.go
Using a variable to ease the fixing process for this particular test.
=> ci: Using variable for long test parameter

client_base.go, client_common_test.go, client_test.go, client_v0.go, client_v0_test.go
Added ability to pass additional headers as a map in a context `additionalHeaders` variable
=> feat: Fir 38088 allow passing custom headers in the go sdk

.github/workflows/nightly-v1.yml, .github/workflows/nightly-v2.yml, .github/workflows/release.yml
3.7 is no longer supported and throws an error now from one of the dependencies
=> build: Bump python version to 3.9

connection_common_integration_test.go, connection_integration_test.go
=> test: Move geography test to 2.0 only

connection_integration_test.go, rows.go, rows_test.go
- Added support for struct type
- Minor testing improvements
=> feat: Fir 38128 ecosystem support for struct type for go sdk

.github/workflows/release.yml
Fixed version variable name used to update the version
=> ci: fix version variable

.github/workflows/code-check.yml, client/auth_common_integration_test.go, connection_common_integration_test.go, utils.go
Fixed handling of an empty query
=> fix: FIR-45327 go sdk streaming fails on empty query

.github/workflows/code-check.yml, client/client_common_test.go, client/client_test.go, client/client_v0_test.go, client/http_client.go, client/user_agent_test.go, driver_test.go, errors/structured_error.go, errors/structured_error_test.go, logging/logger.go, rows/firebolt_decimal_test.go, rows/parser.go, rows/stream_rows.go, statement/parser.go, statement/statement_test.go, utils/test_utils.go
Updated golangci-lint to 2.2.1. Fixed all new issues reported by it
=> ci(NoTicket): Update golangci-lint to 2.2.1

README.md, client/client.go, client/client_base.go, client/client_test.go, connection.go, connection_common_integration_test.go, connection_integration_core_test.go, connection_integration_test.go, connection_test.go, driver.go, statement/parser.go
- Added support for `Firebolt-Remove-Header` parameter, that automatically enables transactions
- Implemented go native interface for transaction execution
=> feat(FIR-46460): support transactions in go sdk
