- client.go
- rows.go
- rows_test.go
Some improvements for ironsource poc:
1. Accept null values event if column type is not nullable
2. Propagate engine error messages to user (we currently just mention that we got 500)
> fix: Ironsource improvements

- .github/workflows/code-check.yml
- .legitignore
- .pre-commit-config.yaml
- auth.go
- auth_integration_test.go
- client.go
- client_test.go
- connection_integration_test.go
- go.mod
- go.sum
- urls.go
The purpose of this PR is to add token caching for the GO SDK.
With this cache, newly created connections will reused an existing access token (when available), and fetch a new one if the token is not available. Also, a new token will be fetched upon expiry or when a 401 is returned by the server.
client_test.go was added in order to test the lifecycle of the tokens (when fetched, when they expired and when the server returns a 401)
> feat: add token caching

- .github/workflows/performance-tests.yml
- performance_test.go
- scripts/performance_test_init.go
What it does:
- Add performance tests using gobenchdata
- There are two series of tests (one with SELECT 1; and another one using the lineitem table). Each test is executed with 1 and 5 threads.
- All the results are stored in the branch gh-pages
- Tests results can be found at https://docs.firebolt.io/firebolt-go-sdk/benchmark/
> feat: add performance test (FIR-17551)

- .github/workflows/integration-tests.yml
- .github/workflows/nightly-v0.yml
- .github/workflows/nightly.yml
Fixing the timeouts we're getting with the system engine tests. They take ~12min in other repos, GO has default timeout of 10m.
> test: fix system engine timeouts

- .github/workflows/integration-tests.yml
Update integration testing workflow to use a new setup action v2, which creates new identity engines and databases
> ci: use new identity integration setup action

- client.go
- driver.go
- urls.go
Removed `dynamic/query` suffix from system engine query execution
> fix: remove dynamic/query suffix

- utils.go
- utils_test.go
UserAgent string is used for statistics gathering only. Some customers reported issues with it in Docker. This allows the code to carry on with the execution.
> fix: Carry on executing when UA string gen fails

- driver_integration_test.go
- rows.go
- rows_test.go
Added support for `nan` and `inf` (both positive and negative) values, coming from backend. They are converted to `math.NaN` and `math.Inf` values
> feat: add support for nan and inf

- connection_integration_test.go
- utils.go
- utils_test.go
Fixed value formatting issues
- Fixed time format, removed the timezone from string and added converting time to UTC before formatting. This results in the same data being stored in db, but this format is also supported by timezone unaware types.
- Removed the precision limit when formatting float values. It used to be 6 digits, not it's all the digits present in the value
- Added support for bytea formatting
> fix: fix time and float formatting issues

- dsn.go
- dsn_test.go
Updated DSN parser to use regexp under the hood to add support for special symbols in password
> feat: Use regex parsing for dsn

- .github/workflows/integration-tests-v2.yml
- .github/workflows/integration-tests.yml
- .github/workflows/nightly-v2.yml
- .github/workflows/release.yml
Updated secret names to use global secrets:
- `FIREBOLT_CLIENT_ID_NEW_IDN` -> `FIREBOLT_CLIENT_ID_DEV_NEW_IDN`
- `FIREBOLT_CLIENT_SECRET_NEW_IDN` -> `FIREBOLT_CLIENT_SECRET_DEV_NEW_IDN`
Also, added missing secrets when calling integration tests from a release action
> ci: update secret names

- auth.go
- client.go
- client_base.go
- client_common_test.go
- client_integration_test.go
- client_integration_v0_test.go
- client_test.go
- client_v0.go
- client_v0_test.go
- connection.go
- connection_common_integration_test.go
- connection_integration_test.go
- connection_test.go
- driver.go
- driver_integration_test.go
- driver_integration_v0_test.go
- driver_test.go
- performance_test.go
This PR aims to add support for USE DATABASE statement for go sdk. However, this change also led to a couple of improvements that needed to be done:
- Add driver-level caching of set parameters and database parameter. This was needed since parameters currently can potentially be lost between each query execution. This is due to `database/sql` underlying behavior. We didn't notice this before because we didn't use `sql.Open` in integration tests.
- Updated integration tests to use `sql.Open` in most cases. This leads to a propper functionality check since it's the way users interact with the driver
> feat: Fir 28441 support use database statement

- connection.go
- connection_test.go
- utils.go
FIR-30143
Some set parameters are not allowed. Adding an appropriate error message for them.
Only unit tests as integration tests are not applicable here since this is a client side check.
> feat: Parameter deny list

- client_integration_v0_test.go
- connection_common_integration_test.go
- utils.go
- utils_test.go
- Implement a universal bytea formatting for both `standard_conforming_strings` enabled and disabled
- Added fixes for long query test
> fix: bytea formatting for new ff

- client.go
- client_integration_test.go
- client_test.go
- connection_test.go
- driver_integration_test.go
- driver_options.go
- driver_options_integration_test.go
- driver_options_test.go
- utils.go
Add support for a new system engine url format, which can contain account_id as a query_parameter as well as a part of a URL (or neither).
This includes:
- accounting for query parameters, that come with a system engine url, and using them later
- allowing account_id set parameter
> feat: Fir 31840 dont append account id for system engine url in go sdk

- .github/workflows/nightly-v1.yml
- .github/workflows/nightly-v2.yml
There's currently a bug with macos-latest and certain versions of Python so we need to pin macos runners to the one behind latest.
> ci: pin macos runners to 13

- connection_common_integration_test.go
Fixing this constant to be in line with Python SDK, where a similar test seems to work well without failures.
> test: Align slow test param with other sdks

- .github/workflows/nightly-v1.yml
- .github/workflows/nightly-v2.yml
Since only this repo nightlies are failing sporadically I'm trying to test if the timing of the run is affecting it.
Other nightlies currently run 3am onwards so setting this one to 2am.
> ci: Reschedule nightly runs to 2am UTC

- client.go
- connection_integration_test.go
- driver_integration_test.go
- driver_integration_v0_test.go
Added quoted identifiers where needed
- USE ENGINE/USE DATABASE commands during connection
- Tests setup/cleanup
> fix: Fir 33266 use quoted identifiers in go sdk

- utils.go
- utils_test.go
As the title says. There is no need to execute queries only have spaces, tabs or lineends in them
> fix: ignore empty parts in multistatement queries

- connection.go
- connection_test.go
When using consecutive SET statements they should use all the previously defined parameters when verifying correctness, since some of the statements enable others.
> fix: Combining set statements

- connection_integration_test.go
Same issue, defer query fails but we never check it.
The failure was due to trying to drop still running engine.
> test: Fix engine cleanup bug

- connection_common_integration_test.go
- connection_integration_test.go
- connection_integration_v0_test.go
We have to split those tests as 1.0 still uses separate DOUBLE and FLOAT formats.
The tests are working now, only failures are on "long" tests.
https://github.com/firebolt-db/firebolt-go-sdk/actions/runs/9894962613
https://github.com/firebolt-db/firebolt-go-sdk/actions/runs/9894960712
> test: split tests that differ from v0

- README.md
- client.go
- client_base.go
- client_test.go
- client_v0.go
- client_v0_test.go
- driver_integration_test.go
- urls.go
Removed account resolve call from the client initialization. Also removed account id validation when the endpoint is updated from the backend after USE ENGINE command
> refactor: FIR-35471 remove account resolve call

- README.md
- driver_integration_test.go
Someone stumbled upon us not supporting named parameters. We should make it clear what kind of queries we can and can't run.
> docs(FIR-36644): Clarify named parameters usage

- rows.go
- rows_test.go
Fixed support for fields with spaces in struct type
> fix: Fir 38128 ecosystem support for struct type for go sdk

- connection_integration_test.go
- go.mod
- go.sum
- rows.go
- rows_test.go
- Added support for decimal type, both as a float and as a string value.
- Added test cases for bigint value returned as a string
> feat: FIR-42569 support quoted decimals in go sdk

- client/client.go
- client/client_v0.go
- driver_options.go
- driver_options_integration_test.go
- driver_options_test.go
A couple of improvements for pg_fire
1. Hardcoded newVersion value for every client type. Otherwise we got into a situation, where we has ClientImpl have newVersion=false, which caused issues when streaming
2. Split driver client options into three different function for a more granular control
> fix: FIR-44362 split driver client options 

- client/client.go
- client/client_base.go
- client/client_v0.go
- connection.go
- driver_options_integration_test.go
Fix issue with client not being initialized properly in ConnectorWithOptions method. This caused v2 client to set newVersion=false, which caused integrity issues during streaming (client requested streaming, but tried to read the response with inMemory rows)
> fix: Fir 44362 fix streaming with driver options

- README.md
- client/auth.go
- client/auth_common_integration_test.go
- client/auth_integration_test.go
- client/auth_integration_v0_test.go
- client/client.go
- client/client_base.go
- client/client_test.go
- client/client_v0_test.go
- client/http_client.go
- client/user_agent.go
- connection.go
- driver.go
- driver_common_integration_test.go
- driver_integration_test.go
- driver_integration_v0_test.go
- driver_options_integration_test.go
- errors/errors.go
- errors/nested_error.go
- errors/nested_error_test.go
Added typed errors to distinguish between issues
- AuthenticationError - when 401/403/400 returned for an authentication request
- QueryExecutionError - generic error for when query execution has failed
- SystemEngineResolutionError - failed to get the system engine for an account
- DSNParsingError - failed to parse DSN
> feat: FIR-44820 add typed errors to go sdk

- .github/workflows/code-check.yml
pre-commit action is using deprecated caching and is maintenance-only so switch to running pre-commit manually.
> ci(NoTicket): fix pre commit action

- data_types_common_integration_test.go
- rows/column_reader_test.go
- rows/firebolt_array.go
- rows/firebolt_struct.go
- utils/test_utils.go
`any` and `math.MaxInt` are not compatible with Go versions before 1.18 so changing it to a compatible syntax, since we want to be compatible with 1.16 and up.
Spotted this issue in nightly.
> fix(NoTicket): fix compatibility with 1.16

- client/client_integration_v0_test.go
- client/client_v0.go
- driver_options.go
- driver_options_integration_test.go
Added new options for custom driver configuration
- WithAccountName
- WithDatabaseAndEngineName
Also options can return errors now, and those options should be used with `FireboltConnectorWithOptionsWithErrors `
> feat: FIR-45303 go sdk extend driver options api

- connection_common_integration_test.go
- go.mod
- go.sum
- utils.go
Extended our parser to consider strings like `";"`, `" ; "`, `";;;"` as empty queries (rather than no query at all). Confirmed the exact same behavior with postgres go client.
> fix: FIR-45327 go sdk streaming failes on empty query

- .github/workflows/integration-test-core.yml
- .github/workflows/integration-tests-v2.yml
- .github/workflows/nightly-v2.yml
- Updated nightly jobs to dynamically determine the stable go versions that are non-deprecated and use them for testing. No need to test on sunsetted version
- Use the latest go version on integration tests for cloud and core 
This API is used to determine go versions - https://go.dev/dl/?mode=json
> ci(NoTicket): Update go versions

- .github/workflows/code-check.yml
- .github/workflows/nightly-v1.yml
The last 2 supported versions of go are: 1.24.x and 1.25.x.
We were trying to run the nightly v1 with 1.16, 1.17, 1.18 and 1.19. These latest supported versions are evolving so use the same pattern as v2 does to query and get which are the supported versions. 
Changed the name of the run to: Nightly code check V1
Also use the v.1.25.1 (latest) when running code check rather than 1.18.0
Ran the nightly's from a local branch to make sure they pass: https://github.com/firebolt-db/firebolt-go-sdk/actions/runs/18160376523
> ci(NoTicket): Fix the v1 nightly integration tests
